# Generated by Django 5.2.8 on 2026-01-24 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='technicien',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicien_demandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
